{{- if and .Values.collector.enabled .Values.collector.useDaemonset }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name : {{ template "wavefront.fullname" . }}
    helm.sh/chart: {{ template "wavefront.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io.instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: collector
  name: {{ template "wavefront.collector.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name : {{ template "wavefront.fullname" .}}
      app.kubernetes.io/component: collector
{{ if .Values.collector.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.collector.updateStrategy | indent 4 }}
{{ end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name : {{ template "wavefront.fullname" .}}
        app.kubernetes.io/component: collector
    spec:
      tolerations:
      - effect: NoSchedule
        key: node.alpha.kubernetes.io/role
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
{{ if .Values.collector.tolerations }}
{{- toYaml .Values.collector.tolerations | indent 6 }}
{{ end }}
      serviceAccountName: {{ template "wavefront.collector.serviceAccountName" . }}
      containers:
      - name: wavefront-collector
        image: {{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}
        imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
        command:
        - /wavefront-collector
        - --agent=legacy
        - --config-file=/etc/collector/config.yaml
        {{- if .Values.collector.maxProcs }}
        - --max-procs={{ .Values.collector.maxProcs }}
        {{- end }}
        {{- if .Values.collector.logLevel }}
        - --log-level={{ .Values.collector.logLevel }}
        {{- end }}
        env:
        - name: HOST_PROC
          value: /host/proc
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8088
          protocol: TCP
        resources:
{{ toYaml .Values.collector.resources | indent 10 }}
        volumeMounts:
        {{- if not .Values.openshift.enabled }}
        - name: procfs
          mountPath: /host/proc
          readOnly: true
        {{- end }}
        - name: config
          mountPath: /etc/collector/
          readOnly: true
    {{- if .Values.collector.priorityClassName }}
      priorityClassName: {{ .Values.collector.priorityClassName }}
    {{- end }}
      volumes:
      {{- if not .Values.openshift.enabled }}
      - name: procfs
        hostPath:
          path: /proc
      {{- end }}
      - name: config
        configMap:
          name: {{ template "wavefront.collector.fullname" . }}-config
{{- end }}
