apiVersion: v1
kind: ServiceAccount
metadata:
  name: wavefront-collector-operator
  namespace: wavefront-collector 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wavefront-collector-operator
  namespace: wavefront-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wavefront-collector-operator
subjects:
- kind: ServiceAccount
  name: wavefront-collector-operator
  namespace: wavefront-collector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavefront-collector-operator
  namespace: wavefront-collector
rules:
- apiGroups:
  - wavefront.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  - nodes/stats
  - services
  - serviceaccounts
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - "*"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-collector-operator
  namespace: wavefront-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wavefront-collector-operator
  template:
    metadata:
      labels:
        name: wavefront-collector-operator
    spec:
      serviceAccountName: wavefront-collector-operator
      containers:
        - name: wavefront-collector-operator
          # Replace this with the built image name
          image: wavefronthq/wavefront-kubernetes-collector-operator:v0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wavefront-collector-operator"
