bases:
  - ../../../deploy/kubernetes

resources:
- proxy.yaml

images:
- name: wavefronthq/wavefront-kubernetes-collector
  newName: DOCKER_HOST/wavefront-kubernetes-collector
  newTag: YOUR_IMAGE_TAG

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: collector-config
    namespace: wavefront-collector
    behavior: replace
    files:
      - collector.yaml