bases:
  - ../../../deploy/kubernetes

resources:
- proxy.yaml

images:
- name: projects.registry.vmware.com/tanzu_observability/kubernetes-collector
  newName: DOCKER_HOST/kubernetes-collector-dev-snapshot
  newTag: YOUR_IMAGE_TAG

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: collector-config
    namespace: wavefront-collector
    behavior: replace
    files:
      - collector.yaml