FROM harbor-repo.vmware.com/dockerhub-proxy-cache/bitnami/golang:1.18 as builder

# Base Setup
ARG BINARY_NAME
WORKDIR /
# Copy the Go Modules manifests

# Copy `go.mod` for definitions and `go.sum` to invalidate the next layer
# in case of a change in the dependencies
COPY go.mod go.sum ./

# Copy src
COPY . ./wavefront-collector-src

# RUN apt-get update && apt-get install -y curl
RUN mv ./wavefront-collector-src/collector-with-restart.sh wavefront-collector

# probably create sub dir for src and pop into it to run tests because of permissions nonsense

ENTRYPOINT ["/wavefront-collector"]
