FROM harbor-repo.vmware.com/dockerhub-proxy-cache/bitnami/golang:1.18 as builder

# Base Setup
ARG BINARY_NAME
WORKDIR /
# Copy the Go Modules manifests

# Copy `go.mod` for definitions and `go.sum` to invalidate the next layer
# in case of a change in the dependencies
COPY go.mod go.sum ./

# Copy src
COPY . .

# RUN apt-get update && apt-get install -y curl
RUN mv ./collector-with-restart.sh wavefront-collector

#   nobody:nobody
ENTRYPOINT ["/wavefront-collector"]
