FROM registry.access.redhat.com/ubi7/go-toolset:1.16.7-3 as builder

ARG LDFLAGS

SHELL ["/bin/bash", "-c"]

WORKDIR /workspace

COPY . .

RUN CGO_ENABLED=0 go build -ldflags "$LDFLAGS" -o ./wavefront-collector ./cmd/wavefront-collector/

#Using ubi7 minimal image
FROM registry.access.redhat.com/ubi7/ubi-minimal:latest

ARG COLLECTOR_VERSION

MAINTAINER wavefront@vmware.com

LABEL name="Wavefront Collector" \
      vendor="Wavefront by VMware" \
      version="$COLLECTOR_VERSION" \
      release="1" \
      run='' \
      summary="The Wavefront Collector for Kubernetes enables monitoring Kubernetes clusters and sending metrics to Wavefront." \
      description="The Wavefront Collector collects real-time metrics from all layers of a Kubernetes environment and Auto discovery of pods and services based on annotation and configuration."

RUN mkdir /licenses

COPY LICENSE /licenses/license.txt

RUN mkdir -p /etc/collector

#COPY deploy/examples/openshift-config.yaml /etc/collector/collector.yaml

COPY --from=builder /workspace/wavefront-collector /

#   nobody:nobody
USER 65534:65534
ENTRYPOINT ["/wavefront-collector"]
