FROM mcr.microsoft.com/windows/servercore:ltsc2019

MAINTAINER wavefront@vmware.com

LABEL name="Wavefront Collector" \
      vendor="Wavefront by VMware" \
      version="1.0.4" \
      release="1" \
      run='' \
      summary="The Wavefront Collector for Kubernetes enables monitoring Kubernetes clusters and sending metrics to Wavefront." \
      description="The Wavefront Collector collects real-time metrics from all layers of a Kubernetes environment and Auto discovery of pods and services based on annotation and configuration."

COPY wavefront-collector /

ENTRYPOINT ["c:\wavefront-collector"]
