FROM registry.access.redhat.com/ubi8/go-toolset:1.16.12-4 as builder
USER root

WORKDIR /workspace

COPY . .

RUN /bin/bash -c "go version"

RUN /bin/bash -c "CGO_ENABLED=0 go build -ldflags '-w -X main.version=1.9.0' -o ./wavefront-collector ./cmd/wavefront-collector/"

#Using ubi8 minimal image
FROM registry.access.redhat.com/ubi8-minimal:latest

MAINTAINER wavefront@vmware.com

LABEL name="Wavefront Collector" \
      maintainer="wavefront@vmware.com" \
      vendor="Wavefront by VMware" \
      version="v1.9.0" \
      release="v1.9.0" \
      summary="The Wavefront Collector for Kubernetes enables monitoring Kubernetes clusters and sending metrics to Wavefront." \
      description="The Wavefront Collector collects real-time metrics from all layers of a Kubernetes environment and Auto discovery of pods and services based on annotation and configuration."

RUN microdnf install yum \
  && yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical \
  && yum clean all \
  && microdnf clean all

RUN mkdir /licenses

COPY LICENSE /licenses/license.txt

RUN mkdir -p /etc/collector

#COPY deploy/examples/openshift-config.yaml /etc/collector/collector.yaml

COPY --from=builder /workspace/wavefront-collector /

#   nobody:nobody
USER 65534:65534
ENTRYPOINT ["/wavefront-collector"]
