apiVersion: v1
kind: Secret
metadata:
  name: memcached-config
  namespace: wavefront-collector
  annotations:
    # This annotation is required for runtime configurations
    wavefront.com/discovery-config: 'true'
stringData:
  collector.yaml: |
    # specify a list of discovery rules (plugins)
    plugins:
    # memcached
    - name: memcached
      type: telegraf/memcached
      selectors:
        images:
        - 'memcached:*'
      port: 11211
      conf: |
        servers = ["${host}:${port}"]
