resource_types:
  - name: gitlab
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/gitlab-resource
      tag: 1.0.0

resources:
  - name: wavefront-collector
    type: git
    source:
      uri: git@github.com:wavefrontHQ/wavefront-collector-for-kubernetes.git
      branch: K8SSAAS-1145-migrate-to-osspi
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
jobs:
  - name: osspi-scan
    serial: true
    plan:
      - in_parallel:
          - get: wavefront-collector
            params: { submodules: all }
      - in_parallel:
        - task: osspi-scan-docker
          file: wavefront-collector/osspi/tasks/osspi/run-osspi-docker.yaml
          input_mapping:
            ci_repo: wavefront-collector
          params:
            IMAGE: projects.registry.vmware.com/tanzu_observability_keights_saas/kubernetes-collector-snapshot
            TAG: passed
            OSM_ENVIRONMENT: beta
            API_KEY: ((osspi.osm-api-key)) # TODO separate beta and prod keys
            ENDPOINT: https://osm-beta.eng.vmware.com/
            USERNAME: ((osspi.osm-username)) # TODO create OSM service account bot
            PRODUCT: WavefrontKubernetesCollector
            VERSION: Latest
            APPEND: true
        - task: osspi-scan-wavefront-collector
          file: wavefront-collector/osspi/tasks/osspi/run-osspi-source.yaml
          input_mapping:
            ci_repo: wavefront-collector
            project_repo: wavefront-collector
          params:
            REPO: project_repo
            OSM_ENVIRONMENT: beta
            API_KEY: ((osspi.osm-api-key)) # TODO separate beta and prod keys
            USERNAME: ((osspi.osm-username)) # TODO create OSM service account bot
            PRODUCT: WavefrontKubernetesCollector
            VERSION: Latest
            PREPARE: |
              go mod vendor
            OSSPI_SCANNING_PARAMS: |
              enable: true
              include_bomtools: "go_mod"
              search_depth: 5
              go_mod.path: "/go/bin/go"

              # exclude for signature scans
              exclude_patterns:
                - vendor
            OSSPI_IGNORE_RULES: |
              - name_regex: onsi\/ginkgo
                version_regex: .*
              - name_regex: gomega
                version_regex: .*
