# Need to change YOUR_CLUSTER and YOUR_API_TOKEN accordingly

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
spec:
  template:
    spec:
      containers:
      - name: wavefront-proxy
        env:
        - name: WAVEFRONT_URL
          value: https://YOUR_CLUSTER.wavefront.com/api/
        - name: WAVEFRONT_TOKEN
          value: YOUR_API_TOKEN
