kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wavefront-collector
subjects:
- kind: ServiceAccount
  name: wavefront-collector
  namespace: wavefront-collector
