# Modify YOUR_K8S_CLUSTER_NAME and YOUR_EXTERNAL_EVENTS_ENDPOINT
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: wavefront-collector
data:
  collector.yaml: |
    clusterName: YOUR_K8S_CLUSTER_NAME
    enableEvents: true
    enableDiscovery: true

    # An External event endpoint to send k8s Events. Ex: http://external-events-endpoint.com/events (No event metrics will be reported to wavefront)
    sinks:
    - externalEventsEndpoint: YOUR_EXTERNAL_EVENTS_ENDPOINT

    sources:
      # The Wavefront Kubernetes dashboards rely on the "kubernetes." prefix by default. See https://docs.wavefront.com/wf_kubernetes_troubleshooting.html for more details.
      kubernetes_source:
        url: 'https://kubernetes.default.svc'
        kubeletPort: 10250
        kubeletHttps: true
        useServiceAccount: true
        insecure: true
        prefix: 'kubernetes.' # Default prefix

        filters:
          metricDenyList:
          - 'kubernetes.sys_container.*'
